### ISSUE TITLE
IFTTT Configuration

### ISSUE THREAD

**Issue by JohnB7777** [eouia/MMM-Whereis#1]
Hello,

I install this module but it doesn't work.
Maybe I did wrong configuration on IFTTT.

At the step 2, URL, can I made my own raspberry pi IP ? (It's a static IP)
For example : 192.168.1.3/whereis

Also, another thing, can I made two IFTTT location for one user ?
For example : 
{
 "who": "dad",
 "location": "Office",
 "EnteredOrExited": {{EnteredOrExited}}
}
_and :_
{
 "who": "dad",
 "location": "Home",
 "EnteredOrExited": {{EnteredOrExited}}
}

And, last thing, I don't understand why the size of the font is big on my mirror.
How can I reduce them ? I try to modify some stuffs on the css file but none work.

Thanks for your answers ! :)

**Comment by JohnB7777** [comment]
Hello,

Do you have any news ?

Thanks

**Comment by sidevil** [comment]
> Hello,
> 
> I install this module but it doesn't work.
> Maybe I did wrong configuration on IFTTT.
> 
> At the step 2, URL, can I made my own raspberry pi IP ? (It's a static IP)
> For example : 192.168.1.3/whereis
> 
> Also, another thing, can I made two IFTTT location for one user ?
> For example :
> {
> "who": "dad",
> "location": "Office",
> "EnteredOrExited": {{EnteredOrExited}}
> }
> _and :_
> {
> "who": "dad",
> "location": "Home",
> "EnteredOrExited": {{EnteredOrExited}}
> }
> 
> And, last thing, I don't understand why the size of the font is big on my mirror.
> How can I reduce them ? I try to modify some stuffs on the css file but none work.
> 
> Thanks for your answers ! :)

192.168.1.3/whereis will not work cause that will be only helpful for local area network. 
as in this we are use post method that local address will not work. 

but you can go to https://www.dataplicity.com/ and setup your device for remote control :) 

and about your second question yes you can make two :)

and last question i couldn't understand 

ALL THE BEST :)

**Comment by TATUMTOT** [comment]
So I’m having the issue of the data not being able to post. Here is a test from an IPAD app that i was using,

        
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Error</title>
</head>

<body>
  <pre>SyntaxError: Unexpected token { in JSON at position 61<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/home/pi/MagicMirror/node_modules/body-parser/lib/types/json.js:89:19)<br> &nbsp; &nbsp;at /home/pi/MagicMirror/node_modules/body-parser/lib/read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (/home/pi/MagicMirror/node_modules/body-parser/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/home/pi/MagicMirror/node_modules/body-parser/node_modules/raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/pi/MagicMirror/node_modules/body-parser/node_modules/raw-body/index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:182:13)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1090:12)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:63:19)</pre>
</body>

</html>
